import "server-only";

import path from "node:path";
import fs from "node:fs/promises";

export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;

const IMAGE_FORMATS = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
} as const;

export type SupportedImageMime = keyof typeof IMAGE_FORMATS;

export function dataDirectory(): string {
  return process.env.DANKE_DATA_DIR
    ? path.resolve(process.env.DANKE_DATA_DIR)
    : path.join(process.cwd(), "data");
}

export function mediaDirectory(): string {
  return path.join(dataDirectory(), "media");
}

export async function ensureMediaDirectory(): Promise<string> {
  const directory = mediaDirectory();
  await fs.mkdir(directory, { recursive: true });
  return directory;
}

export function extensionForMime(mime: SupportedImageMime): string {
  return IMAGE_FORMATS[mime];
}

/** Identify supported image formats from their bytes, not their filename. */
export function detectImageMime(bytes: Uint8Array): SupportedImageMime | null {
  if (
    bytes.length >= 3 &&
    bytes[0] === 0xff &&
    bytes[1] === 0xd8 &&
    bytes[2] === 0xff
  ) {
    return "image/jpeg";
  }

  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a
  ) {
    return "image/png";
  }

  if (
    bytes.length >= 6 &&
    bytes[0] === 0x47 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x38 &&
    (bytes[4] === 0x37 || bytes[4] === 0x39) &&
    bytes[5] === 0x61
  ) {
    return "image/gif";
  }

  if (
    bytes.length >= 12 &&
    bytes[0] === 0x52 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x46 &&
    bytes[8] === 0x57 &&
    bytes[9] === 0x45 &&
    bytes[10] === 0x42 &&
    bytes[11] === 0x50
  ) {
    return "image/webp";
  }

  return null;
}

/** Resolve only storage names generated by the app inside the media folder. */
export function mediaPath(storageName: string): string | null {
  if (!/^[A-Za-z0-9_-]+\.(?:jpg|png|webp|gif)$/.test(storageName)) {
    return null;
  }
  return path.join(mediaDirectory(), storageName);
}

export function safeOriginalName(name: string): string {
  const base = path.basename(name).replace(/[\u0000-\u001f\u007f]/g, "").trim();
  return (base || "image").slice(0, 255);
}
